// Test entry point — every suite registers its tests via a run function.
runSlotGridFloorNextTests()
runSlotGridRangeTests()
runCheckinRulesTests()
runDayStoreInsertTests()
runDayStoreTrimTests()
runDayStoreFazitTests()
runGapFillTests()
runOverlapTests()
runAppUsageTests()
runAnchorAdvanceTests()
runPreferencesLabelTests()
runPreferencesSettingTests()
runStatsMathTests()
runTimeFormattingTests()
runMenuBarPresentationTests()
finishTestRun()
