// Test entry point — every suite registers its tests via a run function.
runSlotGridFloorNextTests()
runSlotGridRangeTests()
runCheckinRulesTests()
runDayStoreInsertTests()
runDayStoreTrimTests()
runDayStoreFazitTests()
runGapFillTests()
runAppUsageTests()
runAnchorAdvanceTests()
runPreferencesTests()
runStatsMathTests()
runTimeFormattingTests()
runMenuBarPresentationTests()
finishTestRun()
